### ISSUE TITLE
FIX: finalise our class names - make sure we're happy they fit well alongside other well known DSL - especially GEM's NRML XML

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-model#15]
@chrisdicaprio the one outstanding change here is the potential rename of FaultSystemLogicTree class to a more generic **BranchSet** (similar to NRML).  A good reason for this is when when create hazard calculations with the combined permutations spanning multiple fault systems.

The implementation is in **nzshm_model.source_logic_tree.version1.logic_tree.** 

Because this will impact the dataclass serialisations, I suggest we decide this before we migrate any more history SLT version into the model.

**Comment by chrisdicaprio** [comment]
@chrisbc are you proposing changes to source logic tree v1 or just v2?
