### ISSUE TITLE
Feature: read SRM model from json

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/nzshm-model#22]
We should separate code from configuration and simplify the definition of SRM logic tree and aslo simplify the way SRM logic trees are defined by the user. This does not change internal classes, it is only a simplification of the config for the user.

- [x] function to read json file equivelent to `nzshm_model.source_logic_tree.slt_config.from_config()
- [x] translate json config to python config (`logic_tree_permuations` and `src_correlations`)
- [x] check that correlations are done correctly (every branch named exists and the primary and secondary fault systems are the same for every pair)

Questions:
should `"fault_system"` be `"branch_set"` instead to be consistent with OQ nrml?

NB: For correlations we no longer specify which group is "dropped". The primary and secondary fault systems are explicitly defined in each correlation on the list.

config.json definition:
```
{
    "title": "a SRM logic tree",
    "version": "SRM_v10.4.0",
    "fault_systems": [
        {
            "name": "Hik",
            "branches": [
                {
                    "tag":  "Hik TL, N16.5, b0.95, C4, s0.42",
                    "weight": 0.147216637218474,
                    "inv_id": "SW52ZXJzaW9uU29sdXRpb25Ocm1sOjExNDQyOA==",
                    "bg_id": "RmlsZToxMzA3MzI="
                },
                {
                    "tag": "Hik TL, N16.5, b0.95, C4, s1",
                    "weight": 0.281154911079988,
                    "inv_id": "SW52ZXJzaW9uU29sdXRpb25Ocm1sOjExNDQxNw==",
                    "bg_id": "RmlsZToxMzA3MzQ="
                }
            ]
        },
        {
            "name": "Puy",
            "branches": [
                {
                    "tag": "Puy 0.7, N4.6, b0.902, C4, s0.28",
                    "weight": 0.21,
                    "inv_id": "SW52ZXJzaW9uU29sdXRpb25Ocm1sOjExODcxNw==",
                    "bg_id": "RmlsZToxMzA3NTM="
                  },
                  {
                    "tag": "Puy 0.7, N4.6, b0.902, C4, s1",
                    "weight": 0.52,
                    "inv_id": "SW52ZXJzaW9uU29sdXRpb25Ocm1sOjExODcyMw==",
                    "bg_id": "RmlsZToxMzA3NTQ="
                  }
            ]
        }
    ],

    "correlations": [
        {
            "primary": {"group": "Hik", "tag": "Hik TL, N16.5, b0.95, C4, s0.42"},
            "secondary": {"group": "Puy", "tag": "Puy 0.7, N4.6, b0.902, C4, s0.28"}
        },
        {
            "primary": {"group": "Hik", "tag": "Hik TL, N16.5, b0.95, C4, s1"},
            "secondary": {"group": "PUY", "tag": "Puy 0.7, N4.6, b0.902, C4, s1"}
        }
    ]
}
```

**Comment by chrisbc** [comment]
Notes:
 - park until we remove FG/BG assumptions
 - get a SLT from any valid json file ( optional replacement for the from_config(python _module )
