### ISSUE TITLE
FaultSystemLogicTree represent branching structure

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/nzshm-model#6]
The `FaultSystemLogicTree` class should represent the full branching structure of the logic tree.
- [ ] class `Branch` --> `EndBranch`
- [ ] class `BranchAtrributeValue` should have a weight (or a weighted version or extension of the class should be created)

That way, the user can define the logic tree by specifying the branching levels (e.g. C value, MFD, deformation model) and their weights and the end branches can be reconstructed on request. This is the way we think about logic trees when building a hazard model.

There is no mechanism to automatically find NRML IDs to make the final logic tree useful. However, we can make the building and manipulation of logic trees easier:
- [ ] With the branching structure defined, output file (csv to make it easy to edit as spreadsheet?) with table of `EndBranch`
- [ ] Column headers are the class member varialbles and the `long_name` of the `BranchAttribueValue` s
- [ ] class methods to read and write the file so that 1) user can define logic tree 2) write file 3) fill in NRML ids 4) read file back in to populate the NRML ids and create a  `SourceLogicTree` object to use for hazard computation 5) alter weights or add/remove branches without having to track spreadsheets manually

**Comment by chrisdicaprio** [comment]
cc: @chrisbc

**Comment by chrisbc** [comment]
superceded in #19
